# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20171224_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='\u0424\u0430\u0439\u043b \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='item',
            name='document_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u0430'),
        ),
    ]
