# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20171225_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='document_name',
        ),
    ]
