# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_item_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('document', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='\u0424\u0430\u0439\u043b')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='document',
        ),
        migrations.AddField(
            model_name='itemdocument',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_item', to='todo.Item', verbose_name='\u0417\u0430\u0434\u0430\u0447\u0430'),
        ),
    ]
